[package]
name = "rectification"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.9.2", features = ["small_rng"] }
rand_distr = "0.5.1"
nalgebra = "0.34.1"
rayon = "1.11.0"

[profile.release]
lto = "fat"
